project:
  type: website

website:
  title: "Winter23 Capstone Projects"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://umairdurrani.com/
        text: Instructor
        target: _blank

format:
  html:
    include-in-header: html/seo.html
    fontsize: 1.1em
    theme: 
      - flatly
      - html/styles.scss
    toc: false
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai



